"""empty message

Revision ID: 8004331492ab
Revises: 93e409dafa6b
Create Date: 2021-10-27 20:04:17.173031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8004331492ab'
down_revision = '93e409dafa6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'category')
    # ### end Alembic commands ###
